version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    ports: 
      - 5000:5000
    env_file: ./frontend/.env
