version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    depends_on:
      - training
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  training:
    build: ./training
    volumes:
      - model:/src/model
      - images:/src/imgs
volumes:
  model:
  images: