version: '3.8'
services:
  redis:
    image: redis
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - ./cache:/data
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  backend:
    build: ./backend
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis